# -*- coding: utf-8 -*-
"""vpn_calculo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sj3YiCHfCWNw0E54qEk7eNLlliw17tN3
"""

import streamlit as st  # Para la interfaz gráfica
import numpy as np  # Para cálculos matemáticos
import matplotlib.pyplot as plt  # Para gráficos

# Configuración del título
st.title("Cálculo del Valor Presente Neto (VPN)")

# Entradas de usuario en el sidebar
with st.sidebar:
    st.header("Datos de entrada")
    inversion_inicial = st.number_input("Inversión inicial:", value=-10000.0, step=100.0)
    tasa_descuento = st.slider("Tasa de descuento (%)", min_value=0.0, max_value=20.0, value=10.0, step=0.1) / 100
    años = st.number_input("Número de años:", min_value=1, max_value=10, value=5, step=1)

    # Entrada de flujos de caja
    flujos = []
    for i in range(int(años)):
        flujo = st.number_input(f"Flujo de caja para el año {i + 1}:", value=2000.0, step=100.0)
        flujos.append(flujo)

# Cálculo del VPN
try:
    vpn = inversion_inicial + sum([flujos[i] / (1 + tasa_descuento)**(i + 1) for i in range(len(flujos))])
    st.write(f"**Valor Presente Neto (VPN):** ${vpn:,.2f}")
except ZeroDivisionError:
    st.error("Error: La tasa de descuento no puede ser cero.")

# Gráfico de flujos de caja
if len(flujos) > 0:
    st.subheader("Visualización de Flujos de Caja")
    fig, ax = plt.subplots()
    ax.bar(range(1, int(años) + 1), flujos, color="blue")
    ax.set_xlabel("Años")
    ax.set_ylabel("Flujo de Caja")
    ax.set_title("Flujos de Caja por Año")
    st.pyplot(fig)
else:
    st.warning("Por favor, ingrese al menos un flujo de caja.")